name: docker

on:
  push:
    branches: [ main ]
    paths:
      - .devcontainer/Dockerfile
      - .github/workflows/docker.yaml
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup version info
        run: echo "VERSION=$(date +%Y%m%d-%H%M%S)-g$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./.devcontainer
          platforms: linux/amd64
          tags: |
            ghcr.io/fermyon/spin-fundamentals/dev-container:${{ env.VERSION }}
